### ISSUE TITLE
Singular Jacobian on Third Indirect Iteration

### ISSUE THREAD

**Issue by cyork765** [msparapa/aae568_project#1]
Andrew noted singular Jacobian on third mission iteration of indirect optimization with EKF nav input.

**Comment by cyork765** [comment]
@adcox @wzaidi Very trial by trial dependent on how many iterations deep it goes. fsolve helped, but does not fix the issue. The problem just has a really difficult time converging after a while.

**Comment by cyork765** [comment]
@wzaidi @adcox Waqar - I think your method of perturbing the truth initially and then only using measurement noise may help.

**Comment by wzaidi** [comment]
try the following code to modify the initial state: 

q     = 1e-5;                    % std dev 
x0    = [a;0;0;w;mdot];    % initial state (truth)
s0    = [x0(1:4)+q*...       % initial state with noise
         randn(4,1);x0(5)];    

Alternatively, we can draw from the initial covariance, C, as follows: 

nSamples  = 1
inSamples = repmat(x0,1,nSamples) + chol(C,'lower')*randn(5,nSamples)

so inSamples becomes your perturbed trajectory but within the uncertainty bounds for the initial state. 

I use this to generate samples for my Monte Carlo.

**Comment by cyork765** [comment]
When I drop Cov(w) down to 1e-12 (1e-6 sigma), no issues converging.

**Comment by cyork765** [comment]
1e-10 converges sometimes

**Comment by wzaidi** [comment]
with the ekf? have you tried the ukf?

**Comment by cyork765** [comment]
Nope. Haven't tried EKF. Is it working on master?

**Comment by cyork765** [comment]
Meant UKF. I'm getting an error when I switch over to it.

**Comment by cyork765** [comment]
Also added time offset to not allow t_now = t_seg -> t_rel_guess = 0. Closing issue. Opening one for nonconvergence.

**Comment by wzaidi** [comment]
i don't have the optimization tool box. I'll need to purchase it and try tonight.

**Comment by wzaidi** [comment]
im getting this error running indirect_main.m with the 'ut' option after installing the optimization tool box:

Error using optimoptions (line 124)
Invalid solver specified. Provide a solver name or handle (such as 'fmincon' or @fminunc).
Type DOC OPTIMOPTIONS for a list of solvers.

Error in indirect_fcn (line 48)
options = optimoptions('fsolve','TolFun',1e-11,'TolX',1e-11,'MaxFunctionEvaluations',1000,'MaxIterations',1000);

Error in indirect_main (line 165)
            [alpha, alpha_t, tf, t_seg, lambda_seg, plot_opt] = indirect_fcn(Chaser,...

Any ideas?
