### ISSUE TITLE
Negative Eigenvalues?

### ISSUE THREAD

**Issue by adcox** [msparapa/aae568_project#10]
The covariance returned by the UKF on [line 261 of indirect_main.m](https://github.com/msparapa/aae568_project/blob/df0bfbedd0aed38467edd62afb4c8c85dfc6fd9b/code/indirect_main.m#L261) has negative eigenvalues... shouldn't it have positive eigenvalues?

**Comment by adcox** [comment]
I created a branch called `issue_10` to test this. Check the eigenvalues of `Nav.P`.

`Nav.P` is set on line 261 of `indirect_main.m`, as linked above.

**Comment by wzaidi** [comment]
Try Nav.P = 1e-2*eye(4);

This is my action to figure out good initial covariance.

**Comment by adcox** [comment]
That does indeed fix the negative eigenvalue problem, but then the UKF has a really difficult time finding the actual trajectory:

![image](https://user-images.githubusercontent.com/8823281/39075065-ebebeb7e-44c1-11e8-8996-4b584d844424.png)

I'm guessing the fact that we're using range and range-rate as the only measurements plays a role? The code is currently set up to take a measurement every 30 minutes.

**Comment by adcox** [comment]
Interestingly, the EKF performs better with the same initial covariance matrix:

![image](https://user-images.githubusercontent.com/8823281/39075197-9199558e-44c2-11e8-819c-23865d3d3b38.png)

**Comment by wzaidi** [comment]
try taking measurements every minute

**Comment by adcox** [comment]
Still seeing divergence in `theta` and `thetadot`,

![image](https://user-images.githubusercontent.com/8823281/39075699-107e307a-44c5-11e8-88d1-f95ebf213039.png)

**Comment by wzaidi** [comment]
so dumb question, are we thrusting during the measurement update? in my code, i realized the thrust was non-zero and was getting integrated at every time step, this was happening in the ukf od which was causing posterior error.

**Comment by wzaidi** [comment]
my other suggestion would be to try and use the EnKF.

**Comment by adcox** [comment]
I'm not sure what you mean by "during the measurement update." We always propagate the ODEs with nonzero thrust, but don't the measurements occur instantaneously? 

Also, the UKF performs well when the initial covariance is smaller, so I'm not sure that the thrusting is the problem.

**Comment by wzaidi** [comment]
ok i'll have to think more about it more then, the UKF should do better with a larger covariance. i'll have to see if the sigma points are being generated properly with the non-dimensionalization.

**Comment by adcox** [comment]
Hmm ok - Hopefully we're on the same page as far as the UKF implementation goes in `indirect_main.m`. Let me know if you have questions about what we're trying to do there.

**Comment by wzaidi** [comment]
also, going back to your comment about just r,rDot measurements, that might be an issue too. But I found a theta bias in my posterior state. so have to look into that.

**Comment by wzaidi** [comment]
![untitled](https://user-images.githubusercontent.com/29795923/39076185-daa19ca0-44c7-11e8-9ff4-11b5eb114c7c.jpg)

**Comment by adcox** [comment]
Seems to be resolved after commit 82e871e
