### ISSUE TITLE
Fails to Converge with P != 0

### ISSUE THREAD

**Issue by cyork765** [msparapa/aae568_project#8]
Can converge occasionally with P0 = 0, and small acceleration noise (1e-12). Usually fails to converge with higher values.

What are reasonable dimensional values of P0, R, Z?

**Comment by cyork765** [comment]
Reducing sample time is promising.

**Comment by adcox** [comment]
@cyork765 implemented a check into the indirect optimizer to avoid failed optimizations in commit 8e0ecf. I'm resolving this issue since convergence seems to be stable now.
