### ISSUE TITLE
Realistic Covariance

### ISSUE THREAD

**Issue by cyork765** [msparapa/aae568_project#9]
Need realistic covariance values for:

Acceleration Noise (lunar gravity perturbing force order of magnitude?)
Measurement Noise (range and range-rate do not have to be equal stdev)
Initial State Covariance (All states)

**Comment by adcox** [comment]
Fantastic table of various error sources on page 33 of this report/paper:

[https://descanso.jpl.nasa.gov/monograph/series1/Descanso1_C03.pdf](https://descanso.jpl.nasa.gov/monograph/series1/Descanso1_C03.pdf)

I've also seen range errors of 10m - 400m quoted in the Vallado book and a few papers online

Citation: Thornton, C. L., & Border, J. S. (2003). Radiometric tracking techniques for deep-space navigation. Hoboken: Wiley-Interscience.

**Comment by adcox** [comment]
Table of various acceleration magnitudes (gravitational, spherical harmonics, solar perturbation, moon perturbation, etc.) as a function of distance from Earth:

[https://link.springer.com/content/pdf/10.1007%2F978-3-642-58351-3.pdf](https://link.springer.com/content/pdf/10.1007%2F978-3-642-58351-3.pdf)

See section 3.1, pp. 55

Citation: Montenbruk, O., and Gill, E., "Satellite Orbits. Models, Methods and Applications", Springer-Verlag Berlin Heidelberg, 2000, doi:10.1007/978-3-642-58351-3

**Comment by adcox** [comment]
![image](https://user-images.githubusercontent.com/8823281/39061426-2e6f5fce-4492-11e8-8330-6beaa7a5aac9.png)

**Comment by adcox** [comment]
![image](https://user-images.githubusercontent.com/8823281/39061444-3de6a26e-4492-11e8-8e7b-b2f5033dfbfb.png)
